Feature/14 create movie adapter
JaimeBallesta/ArchitectCoders pull request #26
Opened 2021-03-22 20:14 UTC by fppuma

2021-03-23 14:55 UTC, JaimeBallesta commented on app/build.gradle
> +
why has this unnecessary space?

2021-03-23 17:11 UTC, cmauroie requested changes
The solution is not based on the 01-init tag

2021-03-23 17:11 UTC, cmauroie commented on app/build.gradle
> +    }
This already exists on build.gradle

2021-03-23 17:11 UTC, cmauroie commented on app/src/main/res/layout/activity_main.xml
> +</androidx.coordinatorlayout.widget.CoordinatorLayout>
this layout is not necesary update

2021-03-23 17:11 UTC, cmauroie commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.4'
currently not used in the project

2021-03-24 12:52 UTC, juanncode reviewed
Review tag 01 please

2021-03-25 03:54 UTC, fppuma commented on app/src/main/res/layout/activity_main.xml
> +</androidx.coordinatorlayout.widget.CoordinatorLayout>
restored to previous version

2021-03-25 03:54 UTC, fppuma commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.4'
restored to previous version

2021-03-25 13:53 UTC, cmauroie approved these changes
perfect

2021-03-25 15:48 UTC, juanncode approved these changes

2021-03-25 20:48 UTC, JaimeBallesta approved these changes

2021-03-25 21:03 UTC, merged