favorite activity and menu
JaimeBallesta/ArchitectCoders pull request #57
Opened 2021-05-03 00:33 UTC by fppuma

2021-05-03 15:17 UTC, cmauroie requested changes

2021-05-03 15:17 UTC, cmauroie commented on app/src/main/res/layout/activity_favorite.xml
> +            app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
Como la información se debe mostrar como una lista se debe cambiar GridLayoutManager por Linearlayoutmanager

2021-05-03 15:17 UTC, cmauroie commented on app/src/main/java/com/developerideas/myapplication/ui/favorite/FavoriteAdapter.kt
> +        val view = parent.inflate(R.layout.view_movie, false)
Se debe hacer un nuevo item view_movie ya que la vista debe ir de acuerdo al diseño, en este caso la vista es una tarjeta diferente, revisar diseño en la tarjeta de la tarea

2021-05-05 05:53 UTC, fppuma commented on app/src/main/res/layout/activity_favorite.xml
> +            app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
Done!

2021-05-05 05:53 UTC, fppuma commented on app/src/main/java/com/developerideas/myapplication/ui/favorite/FavoriteAdapter.kt
> +        val view = parent.inflate(R.layout.view_movie, false)
Done!

2021-05-10 23:14 UTC, cmauroie approved these changes

2021-05-19 15:06 UTC, juanncode approved these changes

2021-05-28 02:26 UTC, merged